---
# tasks file for macos

- name: MacOS | Tap a Homebrew repository, state present
  community.general.homebrew_tap:
    name: "{{ item }}"
  with_items:
    - "{{ macos_homebrew_tap }}"
    - "{{ macos_homebrew_tap_ext }}"
  tags: ["tap"]

- name: MacOS | Install base soft
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ macos_homebrew_pkg }}"
    - "{{ macos_homebrew_pkg_ext }}"
  tags: ["base"]

- name: MacOS | Install cask soft
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ macos_homebrew_cask_pkg }}"
    - "{{ macos_homebrew_cask_pkg_ext }}"
  tags: ["cask"]

- name: MacOS | Install MAS soft
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  with_items:
    - "{{ macos_mas_pkg }}"
    - "{{ macos_mas_pkg_ext }}"
  tags: ["mas"]

- name: MacOS | Set a hostname
  ansible.builtin.hostname:
    name: "{{ macos_hostname }}.local"
  tags: ["hostname"]
